@startuml
!define RELATIVE_INCLUDE
!include ../C4/C4_Context.puml

title Cхема интеграции приложений

Person(deposit, "Депозитные менеджеры", "Менеджеры бэк офиса специалисты по депозитам")

Person(credit, "Кредитные менеджеры", "Менеджеры бэк офиса ответственные за кредиты")
Person(call_center, "Сотрудники кол-центра", "Сотрудники кол-центра")
Person(front, "Сотрудники работающие в отделениях банка", "Сотрудники работающие в отделениях банка")

Person(it, "Сотрудники IT отдела", "Сотрудники IT отдела")


System(abc, "АБС", "Автоматизированная банковская система")

System(call_system, "Система кол-центра", "Система кол-центра")
System(smc, "CMC-шлюз", "СМС-шлюз телеком-оператора")

System_Ext(telecom, "Телеком-оператор", "Внешний оператор по отправке СМС")


Rel(it, smc, "Обслуживают")
Rel(deposit, abc, "Обрабатывает заявки")
Rel(call_center, call_system, "Заводит обращения")
Rel(call_system, abc, "Передаёт обращения")
Rel(credit, abc, "Использует для оценки кредитного риска")
Rel(front, abc, "Создает депозит")
Rel(abc, smc, "Отправляет сmc сообщение")
Rel(smc, telecom, "Доставка СМС")
@enduml